{
    "category": {
        "1511705561333235792": [
            {
                "message": "!req",
                "regex": true,
                "reply": " accepting lang sa **SFW ; SSFW and S-TOX ; N-TOX** server pre Community servers minimum 100 members. __**2 rep**__ if not met. Shop servers must have __**2 rep**__ <:exclamation:1500377710076104825>Wag send ad kapag walang naghahandle ng ticket, wag makulet ha. "
            },
            {
                "message": "!ad",
                "reply": "punta ka dito tapos copy mo tropa <#1511052450113786006>"
            }
        ]
    }
}
  
